version: '3.9'

networks:
  predictive-maintenance-net:
    driver: bridge

volumes:
  prometheus-data:
    driver: local

services:
  rabbitmq:
    image: rabbitmq:3.11-management
    container_name: rabbitmq
    user: ":"
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - predictive-maintenance-net

  db:
    build:
      context: ../
      dockerfile: ./docker/database/Dockerfile
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -h localhost -p 5432" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - predictive-maintenance-net

  predictive_maintenance:
    build:
      context: ../
      dockerfile: ./docker/predictive_maintenance/Dockerfile
    ports:
      - "8001:8001"
    networks:
      - predictive-maintenance-net



  data_generator:
    build:
      context: ../
      dockerfile: ./docker/data_generator/Dockerfile
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_NAME=postgres
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
    ports:
      - "8000:8000"
    depends_on:
      - db
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -h db -p 5432 -U postgres -d postgres"
        ]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: always
    networks:
      - predictive-maintenance-net

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - prometheus-data:/prometheus
      - ../prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - predictive-maintenance-net

  grafana:
    image: grafana/grafana-enterprise
    user: ":"
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ../grafana:/var/lib/grafana
      - ../grafana/provisioning:/etc/grafana/provisioning
    networks:
      - predictive-maintenance-net

  frontend:
    build:
      context: ../
      dockerfile: ./docker/frontend/Dockerfile
    ports:
      - "3001:3003"
    networks:
      - predictive-maintenance-net