name: Makefile CI

on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "development" ]

jobs:
  build:
      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v3

      - name: Cached LFS checkout
        uses: nschloe/action-cached-lfs-checkout@v1.1.2

      - name: Run build_services
        run: make build_services

  cypress-test:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Cached LFS checkout
        uses: nschloe/action-cached-lfs-checkout@v1.1.2
      
      - name: Start Grafana and Prometheus containers
        run: docker compose -f docker/docker-compose.yaml up grafana prometheus --detach

      - name: Get logs
        run: docker compose -f docker/docker-compose.yaml logs

      - name: Wait 30 seconds
        run: sleep 30s
        shell: bash

      - name: Cypress run
        uses: cypress-io/github-action@v5.3.0

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Cached LFS checkout
        uses: nschloe/action-cached-lfs-checkout@v1.1.2

      - name: Run docker-compose up
        run: docker compose -f docker/docker-compose.yaml up --detach

      - name: Get logs
        run: docker compose -f docker/docker-compose.yaml logs

      - name: Setup Python
        uses: actions/setup-python@v4.5.0
        
      - name: Run pip install
        run: python -m pip install pika --upgrade
        
      - name: Run Python Unit Tests
        run: python3 tests/unit_tests/test_rabbitmq.py
