name: Makefile CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Cached LFS checkout
      uses: nschloe/action-cached-lfs-checkout@v1.1.2

    - name: Run compose_up
      run: make compose_up
